const canvas = document.createElement("canvas");
const ctx = canvas.getContext("2d");
document.body.appendChild(canvas);
canvas.width = 800;
canvas.height = 400;

document.body.style.background = "black";

// Player setup
const player = {
    x: 50,
    y: 300,
    width: 30,
    height: 50,
    color: "cyan",
    dy: 0,
    gravity: 0.5,
    jumpPower: -10,
    grounded: false
};

const platforms = [
    { x: 20, y: 350, width: 200, height: 10 },
    { x: 300, y: 280, width: 150, height: 10 },
    { x: 550, y: 220, width: 120, height: 10 }
];

let keys = {};

document.addEventListener("keydown", (e) => (keys[e.code] = true));
document.addEventListener("keyup", (e) => (keys[e.code] = false));

function update() {
    if (keys["ArrowRight"]) player.x += 5;
    if (keys["ArrowLeft"]) player.x -= 5;
    if (keys["Space"] && player.grounded) {
        player.dy = player.jumpPower;
        player.grounded = false;
    }

    player.dy += player.gravity;
    player.y += player.dy;

    player.grounded = false;
    for (let platform of platforms) {
        if (
            player.y + player.height >= platform.y &&
            player.y + player.height <= platform.y + platform.height &&
            player.x + player.width > platform.x &&
            player.x < platform.x + platform.width
        ) {
            player.grounded = true;
            player.dy = 0;
            player.y = platform.y - player.height;
        }
    }
    if (player.y + player.height >= canvas.height) {
        player.grounded = true;
        player.dy = 0;
        player.y = canvas.height - player.height;
    }
}

function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.fillStyle = player.color;
    ctx.fillRect(player.x, player.y, player.width, player.height);
    
    ctx.fillStyle = "gray";
    for (let platform of platforms) {
        ctx.fillRect(platform.x, platform.y, platform.width, platform.height);
    }
}

function gameLoop() {
    update();
    draw();
    requestAnimationFrame(gameLoop);
}

gameLoop();
